 # Numpy 

In [1]:
# https://numpy.org/doc/stable/user/absolute_beginners.html

In [2]:
import numpy as np
a=np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
#Besides creating an array from a sequence of elements, you can easily create an array filled with 0’s:

np.zeros(2)
 

array([0., 0.])

In [4]:
#Or an array filled with 1’s:

np.ones(2)
 

array([1., 1.])

In [5]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [6]:
#You can create an array with a range of elements:

np.arange(4)

array([0, 1, 2, 3])

In [7]:
#And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number, 
#last number, and the step size.

np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [8]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

np.linspace(0, 10, num=5)
 

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [9]:
#Specifying your data type

#While the default data type is floating point (np.float64), you can explicitly specify which data type you want using the dtype keyword.

x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [10]:
myarr=np.array([1,2,3,4],dtype=np.int64)
myarr

array([1, 2, 3, 4], dtype=int64)

In [11]:
myarr=np.array([1,2,3,4],dtype=np.int64)
myarr[0]

1

In [12]:
#two dimensions array
myarr=np.array([[1,2,3,4]],dtype=np.int64)
myarr[0,1]

2

In [13]:
myarr.shape

#1 row 4 columns

(1, 4)

In [14]:
myarr.dtype


dtype('int64')

 # change value in array

In [15]:
myarr=np.array([[1,2,3,4]],dtype=np.int64)
myarr[0,1]

2

In [16]:
myarr[0,1]=45

In [17]:
myarr 


array([[ 1, 45,  3,  4]], dtype=int64)

In [18]:
myarr.size

4

In [19]:
myarr.sort()
myarr

array([[ 1,  3,  4, 45]], dtype=int64)

# Array Creation: Conversion from other python structures

In [20]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])

In [21]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [0, 3, 1]])

In [22]:
listarray.dtype

dtype('int32')

In [23]:
listarray.shape

(3, 3)

In [24]:
listarray.size

9

In [25]:
np.array({1,2,3})

array({1, 2, 3}, dtype=object)

In [26]:
zeros=np.zeros((2,5))

In [27]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
zeros.dtype

dtype('float64')

In [29]:
zeros.size

10

In [30]:
zeros.shape

(2, 5)

In [31]:
range=np.arange(15)  #0 t0 15

In [32]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [33]:
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

lsspace=np.linspace(0, 20, num=10)  # 0 sa kekr 20 taq equal space element deda ga
 

In [34]:
lsspace

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [35]:
emp=np.empty((4,6)) #4,6 ki range ma empty array (random value) deda ga ap koe value is ma dal sakta ho

In [36]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        2.22521816e-307, 2.78148323e-307, 1.89145198e-307],
       [7.56587584e-307, 1.37961302e-306, 1.05699242e-307,
        8.01097889e-307, 1.78020169e-306, 7.56601165e-307],
       [1.02359984e-306, 1.33510679e-306, 2.22522597e-306,
        1.33511018e-306, 6.23057689e-307, 1.33511290e-306],
       [1.78019082e-306, 8.45559303e-307, 8.06613465e-308,
        6.89810244e-307, 1.22387550e-307, 2.22522596e-306]])

In [37]:
emp_like=np.empty_like(lsspace)    #ya kraga ya apna jo empty array banya ho ga is ka size copy krka aik empty array bnada ga

In [38]:
emp_like

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [39]:
ide=np.identity(40)

In [40]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [41]:
arr=np.arange(99)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [43]:
arr=arr.reshape(3,33)   #3 x33 =99

In [44]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [45]:
arr=arr.ravel()  #array ko seedha krdon 

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [47]:
arr =arr.shape 
arr

(99,)

In [48]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [50]:
ar=np.array(x)

In [51]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [52]:
ar.sum(axis=0)

array([12,  8,  9])

In [53]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [54]:
ar.T #Transpose

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [55]:
 ar.flat   

In [56]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
1
0


In [57]:
ar.ndim  #no of dimensions

2

In [59]:
ar.size

9

In [58]:
ar.nbytes #total bytes consumes

36

In [62]:
one=np.array([1,3,4,634,2])

In [63]:
one.argmax() # ya index batata ha jha pr apki maximum value ha

3

In [64]:
one.argmin() # ya index batata ha jha pr apki minimum value ha

0

In [65]:
one.argsort() # value kaise sort ho iska index bataa ga

array([0, 4, 1, 2, 3], dtype=int64)

In [67]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [69]:
ar.argmin()

8

In [70]:
ar.argmax()

6

In [71]:
ar.argmax(axis=0)

array([2, 1, 1], dtype=int64)

In [72]:
ar.argmax(axis=1)

array([2, 2, 0], dtype=int64)

In [73]:
ar.argsort(axis=1)   #indexing batada for sort

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]], dtype=int64)

In [74]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]], dtype=int64)

In [75]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [76]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [1],
       [0]])

In [78]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [79]:
#matrix operation
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [80]:
[23,44]+[43,22]  #above thongs not done through list in python

[23, 44, 43, 22]

In [82]:
ar


array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [83]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [84]:
ar.sum()

29

In [85]:
ar.max()

7

In [86]:
ar.min()

0

In [88]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [87]:
np.where(ar >5)

#O=(array([1, 2], dtype=int64), array([2, 0], dtype=int64))
# 2 row   3 coloumn              3 row    1 coloumn 

(array([1, 2], dtype=int64), array([2, 0], dtype=int64))

In [89]:
type(np.where(ar >5))

tuple

In [92]:
np.count_nonzero(ar)

8

In [93]:
np.nonzero(ar)
#hr dimension ka lia non zero (yani wo index batada ga jha nonzero element mojood ha)

(array([0, 0, 0, 1, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1], dtype=int64))

In [95]:
ar[1,2]=0

In [96]:
np.nonzero(ar)
#hr dimension ka lia non zero (yani wo index batada ga jha nonzero element mojood ha)

(array([0, 0, 0, 1, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1], dtype=int64))

In [97]:
import sys

In [100]:
py_arr=[0,4,55,2]

In [101]:
np_arr=np.array(py_arr)

In [102]:
sys.getsizeof(1) * len(py_arr)  # 1 array element size multiply by len of array
#python take 112 bytes

112

In [104]:
np_arr.itemsize * np_arr.size
#numpy takes 16 bytes

16

In [106]:
#https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.html